import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expectInvalid, validateFixture } from "../src/intake-validation.js";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const SCHEMA_DIR=path.join(ROOT,"intake","schemas"),FIXTURE_DIR=path.join(ROOT,"intake","fixtures"),ADMIN_BUNDLE=path.join(ROOT,"public","admin","intake-fixtures.json");
const COMMANDS=new Set(["build","check","test"]);function fail(message){throw new Error(message)}
async function readJson(filePath){let text;try{text=await readFile(filePath,"utf8")}catch(error){fail(`${path.relative(ROOT,filePath)}: ${error.message}`)}try{return JSON.parse(text)}catch(error){fail(`${path.relative(ROOT,filePath)}: invalid JSON (${error.message})`)}}
async function loadContract(){const schemas={request:await readJson(path.join(SCHEMA_DIR,"request.schema.json")),analysis:await readJson(path.join(SCHEMA_DIR,"analysis.schema.json"))};if(schemas.request.$schema!=="https://json-schema.org/draft/2020-12/schema"||schemas.analysis.$schema!=="https://json-schema.org/draft/2020-12/schema")fail("Intake schemas must declare JSON Schema draft 2020-12");const names=(await readdir(FIXTURE_DIR)).filter((name)=>name.endsWith(".json")).sort(),fixtures=new Map();for(const name of names)fixtures.set(name,await readJson(path.join(FIXTURE_DIR,name)));return{schemas,fixtures}}
async function checkContract(){const{schemas,fixtures}=await loadContract(),expected=["hold-insufficient-evidence.json","publish-story-005.json","reject-no-systemic-failure.json"];if(JSON.stringify([...fixtures.keys()])!==JSON.stringify(expected))fail(`Expected exactly these golden fixtures: ${expected.join(", ")}`);for(const[name,fixture]of fixtures)validateFixture(fixture,schemas,name);return{schemas,fixtures}}
function serialize(fixtures){return`${JSON.stringify({schema_version:"1.0",fixtures:[...fixtures.entries()].map(([name,fixture])=>({name,request:fixture.request,analysis:fixture.analysis}))},null,2)}\n`}
async function build(){const{fixtures}=await checkContract();await writeFile(ADMIN_BUNDLE,serialize(fixtures),"utf8");return fixtures.size}async function verify(fixtures){let actual;try{actual=await readFile(ADMIN_BUNDLE,"utf8")}catch{fail("public/admin/intake-fixtures.json is missing; run npm run intake:build")}if(actual!==serialize(fixtures))fail("public/admin/intake-fixtures.json is stale; run npm run intake:build")}
async function tests(){const{schemas,fixtures}=await checkContract(),publish=fixtures.get("publish-story-005.json"),hold=fixtures.get("hold-insufficient-evidence.json"),reject=fixtures.get("reject-no-systemic-failure.json"),labels=[];function mutate(label,source,change){const value=structuredClone(source);change(value);expectInvalid(label,value,schemas);labels.push(label)}mutate("publish with unverified material claim",publish,(v)=>{v.analysis.claims[0].verification_status="unverified"});mutate("publish with missing proposed headline",publish,(v)=>{v.analysis.proposed_headline=null});mutate("hold with no hold reasons",hold,(v)=>{v.analysis.hold_reasons=[]});mutate("reject with no reject reasons",reject,(v)=>{v.analysis.reject_reasons=[]});mutate("nonexistent claim-to-source reference",hold,(v)=>{v.analysis.claims[0].source_refs=["missing-source"]});mutate("nonexistent source-to-claim reference",hold,(v)=>{v.analysis.sources[0].claims_supported=["missing-claim"]});mutate("duplicate claim ID",publish,(v)=>{v.analysis.claims.push(structuredClone(v.analysis.claims[0]))});mutate("duplicate source ID",publish,(v)=>{v.analysis.sources.push(structuredClone(v.analysis.sources[0]))});mutate("invalid category",publish,(v)=>{v.analysis.category="Regional"});mutate("severity outside 1–5",publish,(v)=>{v.analysis.severity=6});mutate("invalid URL",hold,(v)=>{v.request.submitted_url="ftp://example.com/not-http";v.analysis.submitted_url=v.request.submitted_url});mutate("request/analysis URL mismatch",hold,(v)=>{v.analysis.submitted_url="https://example.com/different"});mutate("invalid intake origin",publish,(v)=>{v.analysis.intake_origin="unknown"});return labels}
const command=process.argv[2];if(!COMMANDS.has(command)||process.argv.length!==3){console.error("Usage: node scripts/intake.mjs <build|check|test>");process.exit(1)}try{if(command==="build")console.log(`Built admin intake bundle: ${await build()} validated fixtures.`);else if(command==="check"){const{fixtures}=await checkContract();await verify(fixtures);console.log(`Intake contract valid: 2 schemas, ${fixtures.size} golden fixtures, admin bundle current.`)}else console.log(`Intake contract tests passed: 3 golden fixtures, ${(await tests()).length} negative tests.`)}catch(error){console.error(`Intake ${command} failed: ${error.message}`);process.exit(1)}
